In [1]:
%pwd

'D:\\POC\\python\\first'

In [2]:
%pwd?

In [3]:
%timeit 

In [2]:
s='Welcome to Jupyter Notebooks!!!'

In [3]:
s

'Welcome to Jupyter Notebooks!!!'

In [7]:
len(s)

31

In [6]:
s[11:28]

'Jupyter Notebooks'

In [8]:
vowels=['a','e','i','o','u','A','E','I','O','U']
sum(1 for chars in s if chars in vowels)

10

In [11]:
char_s=('J','N')
[word for word in s.split() if word.startswith(char_s)]

['Jupyter', 'Notebooks!!!']

In [4]:
fruits = ['apple', 'mango', 'kiwi', 'watermelon', 'pear']

In [5]:
print(len(fruits))

5


In [6]:
print(fruits)

['apple', 'mango', 'kiwi', 'watermelon', 'pear']


In [7]:
fruits_len=[len(i) for i in fruits]

In [8]:
print(fruits_len)

[5, 5, 4, 10, 4]


In [9]:
fruits_mp=[x for x in fruits if x.startswith('m')==True or x.startswith('p')==True ]

In [37]:
print(fruits_mp)

['mango', 'pear']


In [52]:
_i1

'%pwd'

In [53]:
_i2

'%pwd?'

In [54]:
_i3

'%timeit '

In [55]:
_1

'D:\\POC\\python\\first'

In [57]:
%hist

%pwd
%pwd?
%timeit
fruits = ['apple', 'mango', 'kiwi', 'watermelon', 'pear']
print(len(fruits))
print(fruits)
fruits_len=[len(i) for i in fruits]
print(fruits_len)
fruits_mp=[x for x in fruits if x.startswith('m')==True or x.startswith('p')==True ]
print(fruits_mp)
%save sample_script.py 6-13
%more sample_script.py
%run sample_script.py
%save sample_script.py 4-10
%more sample_script.py
%run sample_script.py
###TEST
import numpy as np
x = np.array([5, 8, 

              9, 10, 

              11]) # using 'array' method
type(x)   # Displays type of array 'x'
x
y = np.array([[6, 9, 5], 

              [10, 82, 34]])  

print(y)
print(y.ndim, y.shape, y.size, y.dtype, y.itemsize, y.nbytes)
z = np.array([[6, 9, 5],

              [10, 82, 34]], 

             dtype='float64')  

print(z)

print(z.dtype)
n = [5, 10, 15, 20, 25]
array_x=np.array(n)
print(type(array_x))
print(array_x.dtype)
print(array_x.ndim,array_x.shape,array_x.size)
n2 = [[-1, -2, -3, -4], [-2,-4, -6, -8]]
array_y=np.arr

In [14]:
%save sample_script.py 4-10


File `sample_script.py` exists. Overwrite (y/[N])?  y
The following commands were written to file `sample_script.py`:
fruits = ['apple', 'mango', 'kiwi', 'watermelon', 'pear']
print(len(fruits))
print(fruits)
fruits_len=[len(i) for i in fruits]
print(fruits_len)
fruits_mp=[x for x in fruits if x.startswith('m')==True or x.startswith('p')==True ]
print(fruits_mp)


In [15]:
%more sample_script.py

In [16]:
%run sample_script.py

5
['apple', 'mango', 'kiwi', 'watermelon', 'pear']
[5, 5, 4, 10, 4]
['mango', 'pear']


# Test
1. one
2. two
### TEST
- one
- two
* three
* four


In [15]:
import numpy as np

In [19]:
x = np.array([5, 8, 

              9, 10, 

              11]) # using 'array' method

In [20]:
type(x)   # Displays type of array 'x'

numpy.ndarray

In [21]:
x

array([ 5,  8,  9, 10, 11])

In [22]:
y = np.array([[6, 9, 5], 

              [10, 82, 34]])  

print(y)


[[ 6  9  5]
 [10 82 34]]


In [23]:
print(y.ndim, y.shape, y.size, y.dtype, y.itemsize, y.nbytes)

2 (2, 3) 6 int32 4 24


In [24]:
z = np.array([[6, 9, 5],

              [10, 82, 34]], 

             dtype='float64')  

print(z)

print(z.dtype)

[[ 6.  9.  5.]
 [10. 82. 34.]]
float64


In [25]:
n = [5, 10, 15, 20, 25]

In [26]:
array_x=np.array(n)

In [27]:
print(type(array_x))

<class 'numpy.ndarray'>


In [28]:
print(array_x.dtype)

int32


In [29]:
print(array_x.ndim,array_x.shape,array_x.size)

1 (5,) 5


In [30]:
n2 = [[-1, -2, -3, -4], [-2,-4, -6, -8]]

In [31]:
array_y=np.array(n2)

In [33]:
print(type(array_x))

<class 'numpy.ndarray'>


In [32]:
print(array_x.dtype)

int32


In [34]:
print(array_y.ndim,array_y.shape,array_y.size,array_y.dtype,array_y.itemsize)

2 (2, 4) 8 int32 4


In [58]:
a = [[[4.1, 2.5], [1.1, 2.3], [9.1, 2.5]], 

     [[8.6, 9.9],[3.6, 4.3], [6.6, 0.3]]]

xx = np.array(a, dtype='float64')

type(xx), xx.ndim, xx.shape


(numpy.ndarray, 3, (2, 3, 2))

In [59]:
xxx = np.zeros(shape=(2,4))

print(xxx)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [60]:
yy = np.full(shape=(2,3), fill_value=10.5)

print(yy)


[[10.5 10.5 10.5]
 [10.5 10.5 10.5]]


In [61]:
b=np.arange(3, 15, 2.5) # 2.5 is step
print(b)

[ 3.   5.5  8.  10.5 13. ]


In [62]:
c = np.linspace(3, 15, 5) # 5 is size of array 'y'

print(c)

[ 3.  6.  9. 12. 15.]


In [63]:
np.random.seed(100) # setting seed

d = np.random.rand(2) # 2 random numbers between 0 and 1

print(d)

[0.54340494 0.27836939]


In [64]:
np.random.seed(100) # setting seed

e = np.random.randint(10, 50, 3) # 3 random integers between 10 and 50

print(e)


[18 34 13]


In [65]:
np.random.seed(100)

f = np.random.randn(3) # Standard normal distribution

print(f)

[-1.74976547  0.3426804   1.1530358 ]


In [66]:
np.random.seed(100)

g = 10 + 2.5*np.random.randn(3) # normal distribution with mean 10 and sd 2

print(g)

[ 5.62558632 10.85670101 12.88258951]


In [12]:
from io import StringIO

In [13]:
stream = StringIO('''88.25 93.45 72.60 90.90

72.3 78.85 92.15 65.75

90.5 92.45 89.25 94.50

''')

In [17]:
data = np.loadtxt(stream,delimiter=' ')

print(data)

print(data.ndim, data.shape)

[[88.25 93.45 72.6  90.9 ]
 [72.3  78.85 92.15 65.75]
 [90.5  92.45 89.25 94.5 ]]
2 (3, 4)


In [18]:
print(np.array(([1, 2], (3,4))).shape)

(2, 2)


In [19]:
 
print(np.eye(2))

[[1. 0.]
 [0. 1.]]


In [22]:
x1=np.array([[[-1,1],[-2,2]],[[-3, 3], [-4, 4]]])

In [23]:
print(x1.ndim,x1.shape,x1.size)

3 (2, 2, 2) 8


In [27]:
x2 = np.full(shape=(3,2,2), fill_value=1)

In [28]:
x3 = np.eye(4)

In [29]:
print(x2)
print(x3)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
np.random.seed(100)
x4 =  np.random.rand(24).reshape((3, 4, 2))

In [36]:
print(x4)

[[[0.54340494 0.27836939]
  [0.42451759 0.84477613]
  [0.00471886 0.12156912]
  [0.67074908 0.82585276]]

 [[0.13670659 0.57509333]
  [0.89132195 0.20920212]
  [0.18532822 0.10837689]
  [0.21969749 0.97862378]]

 [[0.81168315 0.17194101]
  [0.81622475 0.27407375]
  [0.43170418 0.94002982]
  [0.81764938 0.33611195]]]


In [37]:
x5 = 5+2.5*np.random.randn(20)
print(x5)

[3.90466094 2.20420438 9.04745415 8.85401294 4.37030215 2.89391065
 5.46129673 7.3427055  6.82750086 8.40389031 4.18440485 5.13919004
 5.55599902 1.39195751 3.10911924 7.04113503 6.8761119  3.86013268
 7.97405567 0.77345793]


In [38]:
x6=np.arange(0,40,2)
print(x6)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [39]:
x7=np.linspace(10,20,30)
print(x7)

[10.         10.34482759 10.68965517 11.03448276 11.37931034 11.72413793
 12.06896552 12.4137931  12.75862069 13.10344828 13.44827586 13.79310345
 14.13793103 14.48275862 14.82758621 15.17241379 15.51724138 15.86206897
 16.20689655 16.55172414 16.89655172 17.24137931 17.5862069  17.93103448
 18.27586207 18.62068966 18.96551724 19.31034483 19.65517241 20.        ]


In [41]:
np.random.seed(100)

x8 = np.random.randint(10, 100, 8)
print(x8, end='\n\n')


[18 34 77 97 89 58 20 62]



In [42]:
y2 = x8.reshape(2,4)

print(y2, end='\n\n')


[[18 34 77 97]
 [89 58 20 62]]



In [43]:
z2 = x8.reshape(2,2,2)

print(z2, '\n\n')

[[[18 34]
  [77 97]]

 [[89 58]
  [20 62]]] 




In [44]:
x9= np.array([[-1, 1], [-3, 3]])
y3 = np.array([[-2, 2], [-4, 4]])

In [46]:
np.vstack((x9,y3))

array([[-1,  1],
       [-3,  3],
       [-2,  2],
       [-4,  4]])

In [47]:
x10 = np.array([[-1, 1], [-3, 3]])

y4 = np.array([[-2, 2], [-4, 4]])

z3 = np.array([[-5, 5], [-6, 6]])

In [48]:
np.hstack((x10,y4,z3))

array([[-1,  1, -2,  2, -5,  5],
       [-3,  3, -4,  4, -6,  6]])

In [51]:
x = np.arange(30).reshape(6, 5)
print(x,end='\n\n')


res = np.vsplit(x, 2)

print(res[0], end='\n\n')

print(res[1])


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [52]:
x = np.arange(30).reshape(6, 5)

print(x,end='\n\n')

res = np.vsplit(x, (2, 5))

print(res[0], end='\n\n')

print(res[1], end='\n\n')

print(res[2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[25 26 27 28 29]]


In [53]:
x = np.arange(10).reshape(2, 5)
print(x,end='\n\n')


res = np.hsplit(x, (2,4))

print(res[0], end='\n\n')

print(res[1], end='\n\n')

print(res[2])


[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 1]
 [5 6]]

[[2 3]
 [7 8]]

[[4]
 [9]]


In [55]:
x = np.arange(6).reshape(2,3)
print(x)
y = np.hsplit(x,(2,))
print(y[0])

[[0 1 2]
 [3 4 5]]
[[0 1]
 [3 4]]


In [56]:
x=np.arange(20)
print(x.shape)

(20,)


In [62]:
y=x.reshape((2, 10))
print(x,end='\n\n')
print(y,end='\n\n')
np.hsplit(y,2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]



[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]]), array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]])]

In [63]:
z=x.reshape((4, 5))
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [64]:
np.vsplit(z,2)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [68]:
x=np.arange(3,15,3)
print(x)

[ 3  6  9 12]


In [69]:
p=x.reshape(2,2)
print(p)

[[ 3  6]
 [ 9 12]]


In [70]:
x=np.arange(15,33,3)
print(x)

[15 18 21 24 27 30]


In [71]:
q=x.reshape(2,3)
print(q)

[[15 18 21]
 [24 27 30]]


In [74]:
np.hstack((p,q))

array([[ 3,  6, 15, 18, 21],
       [ 9, 12, 24, 27, 30]])