In [1]:
%pwd

'D:\\POC\\python\\first'

In [2]:
%pwd?

In [3]:
%timeit 

In [4]:
s='Welcome to Jupyter Notebooks!!!'

In [5]:
s

'Welcome to Jupyter Notebooks!!!'

In [6]:
len(s)

31

In [7]:
s[11:28]

'Jupyter Notebooks'

In [8]:
vowels=['a','e','i','o','u','A','E','I','O','U']
sum(1 for chars in s if chars in vowels)

10

In [9]:
char_s=('J','N')
[word for word in s.split() if word.startswith(char_s)]

['Jupyter', 'Notebooks!!!']

In [10]:
fruits = ['apple', 'mango', 'kiwi', 'watermelon', 'pear']

In [11]:
print(len(fruits))

5


In [12]:
print(fruits)

['apple', 'mango', 'kiwi', 'watermelon', 'pear']


In [13]:
fruits_len=[len(i) for i in fruits]

In [14]:
print(fruits_len)

[5, 5, 4, 10, 4]


In [15]:
fruits_mp=[x for x in fruits if x.startswith('m')==True or x.startswith('p')==True ]

In [16]:
print(fruits_mp)

['mango', 'pear']


In [17]:
_i1

'%pwd'

In [18]:
_i2

'%pwd?'

In [19]:
_i3

'%timeit '

In [20]:
_1

'D:\\POC\\python\\first'

In [21]:
%hist

%pwd
%pwd?
%timeit
s='Welcome to Jupyter Notebooks!!!'
s
len(s)
s[11:28]
vowels=['a','e','i','o','u','A','E','I','O','U']
sum(1 for chars in s if chars in vowels)
char_s=('J','N')
[word for word in s.split() if word.startswith(char_s)]
fruits = ['apple', 'mango', 'kiwi', 'watermelon', 'pear']
print(len(fruits))
print(fruits)
fruits_len=[len(i) for i in fruits]
print(fruits_len)
fruits_mp=[x for x in fruits if x.startswith('m')==True or x.startswith('p')==True ]
print(fruits_mp)
_i1
_i2
_i3
_1
%hist


In [22]:
%save sample_script.py 10-16


File `sample_script.py` exists. Overwrite (y/[N])?  y
The following commands were written to file `sample_script.py`:
fruits = ['apple', 'mango', 'kiwi', 'watermelon', 'pear']
print(len(fruits))
print(fruits)
fruits_len=[len(i) for i in fruits]
print(fruits_len)
fruits_mp=[x for x in fruits if x.startswith('m')==True or x.startswith('p')==True ]
print(fruits_mp)


In [23]:
%more sample_script.py

In [24]:
%run sample_script.py

5
['apple', 'mango', 'kiwi', 'watermelon', 'pear']
[5, 5, 4, 10, 4]
['mango', 'pear']


# Test
1. one
2. two
### TEST
- one
- two
* three
* four


In [25]:
import numpy as np

In [26]:
x = np.array([5, 8, 

              9, 10, 

              11]) # using 'array' method

In [27]:
type(x)   # Displays type of array 'x'

numpy.ndarray

In [28]:
x

array([ 5,  8,  9, 10, 11])

In [29]:
y = np.array([[6, 9, 5], 

              [10, 82, 34]])  

print(y)


[[ 6  9  5]
 [10 82 34]]


In [30]:
print(y.ndim, y.shape, y.size, y.dtype, y.itemsize, y.nbytes)

2 (2, 3) 6 int32 4 24


In [31]:
z = np.array([[6, 9, 5],

              [10, 82, 34]], 

             dtype='float64')  

print(z)

print(z.dtype)

[[ 6.  9.  5.]
 [10. 82. 34.]]
float64


In [32]:
n = [5, 10, 15, 20, 25]

In [33]:
array_x=np.array(n)

In [34]:
print(type(array_x))

<class 'numpy.ndarray'>


In [35]:
print(array_x.dtype)

int32


In [36]:
print(array_x.ndim,array_x.shape,array_x.size)

1 (5,) 5


In [37]:
n2 = [[-1, -2, -3, -4], [-2,-4, -6, -8]]

In [38]:
array_y=np.array(n2)

In [39]:
print(type(array_x))

<class 'numpy.ndarray'>


In [40]:
print(array_x.dtype)

int32


In [41]:
print(array_y.ndim,array_y.shape,array_y.size,array_y.dtype,array_y.itemsize)

2 (2, 4) 8 int32 4


In [42]:
a = [[[4.1, 2.5], [1.1, 2.3], [9.1, 2.5]], 

     [[8.6, 9.9],[3.6, 4.3], [6.6, 0.3]]]

xx = np.array(a, dtype='float64')

type(xx), xx.ndim, xx.shape


(numpy.ndarray, 3, (2, 3, 2))

In [43]:
xxx = np.zeros(shape=(2,4))

print(xxx)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [44]:
yy = np.full(shape=(2,3), fill_value=10.5)

print(yy)


[[10.5 10.5 10.5]
 [10.5 10.5 10.5]]


In [45]:
b=np.arange(3, 15, 2.5) # 2.5 is step
print(b)

[ 3.   5.5  8.  10.5 13. ]


In [46]:
c = np.linspace(3, 15, 5) # 5 is size of array 'y'

print(c)

[ 3.  6.  9. 12. 15.]


In [47]:
np.random.seed(100) # setting seed

d = np.random.rand(2) # 2 random numbers between 0 and 1

print(d)

[0.54340494 0.27836939]


In [48]:
np.random.seed(100) # setting seed

e = np.random.randint(10, 50, 3) # 3 random integers between 10 and 50

print(e)


[18 34 13]


In [49]:
np.random.seed(100)

f = np.random.randn(3) # Standard normal distribution

print(f)

[-1.74976547  0.3426804   1.1530358 ]


In [50]:
np.random.seed(100)

g = 10 + 2.5*np.random.randn(3) # normal distribution with mean 10 and sd 2

print(g)

[ 5.62558632 10.85670101 12.88258951]


In [51]:
from io import StringIO

In [52]:
stream = StringIO('''88.25 93.45 72.60 90.90

72.3 78.85 92.15 65.75

90.5 92.45 89.25 94.50

''')

In [53]:
data = np.loadtxt(stream,delimiter=' ')

print(data)

print(data.ndim, data.shape)

[[88.25 93.45 72.6  90.9 ]
 [72.3  78.85 92.15 65.75]
 [90.5  92.45 89.25 94.5 ]]
2 (3, 4)


In [54]:
print(np.array(([1, 2], (3,4))).shape)

(2, 2)


In [55]:
 
print(np.eye(2))

[[1. 0.]
 [0. 1.]]


In [56]:
x1=np.array([[[-1,1],[-2,2]],[[-3, 3], [-4, 4]]])

In [57]:
print(x1.ndim,x1.shape,x1.size)

3 (2, 2, 2) 8


In [58]:
x2 = np.full(shape=(3,2,2), fill_value=1)

In [59]:
x3 = np.eye(4)

In [60]:
print(x2)
print(x3)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [61]:
np.random.seed(100)
x4 =  np.random.rand(24).reshape((3, 4, 2))

In [62]:
print(x4)

[[[0.54340494 0.27836939]
  [0.42451759 0.84477613]
  [0.00471886 0.12156912]
  [0.67074908 0.82585276]]

 [[0.13670659 0.57509333]
  [0.89132195 0.20920212]
  [0.18532822 0.10837689]
  [0.21969749 0.97862378]]

 [[0.81168315 0.17194101]
  [0.81622475 0.27407375]
  [0.43170418 0.94002982]
  [0.81764938 0.33611195]]]


In [63]:
x5 = 5+2.5*np.random.randn(20)
print(x5)

[3.90466094 2.20420438 9.04745415 8.85401294 4.37030215 2.89391065
 5.46129673 7.3427055  6.82750086 8.40389031 4.18440485 5.13919004
 5.55599902 1.39195751 3.10911924 7.04113503 6.8761119  3.86013268
 7.97405567 0.77345793]


In [64]:
x6=np.arange(0,40,2)
print(x6)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [65]:
x7=np.linspace(10,20,30)
print(x7)

[10.         10.34482759 10.68965517 11.03448276 11.37931034 11.72413793
 12.06896552 12.4137931  12.75862069 13.10344828 13.44827586 13.79310345
 14.13793103 14.48275862 14.82758621 15.17241379 15.51724138 15.86206897
 16.20689655 16.55172414 16.89655172 17.24137931 17.5862069  17.93103448
 18.27586207 18.62068966 18.96551724 19.31034483 19.65517241 20.        ]


In [66]:
np.random.seed(100)

x8 = np.random.randint(10, 100, 8)
print(x8, end='\n\n')


[18 34 77 97 89 58 20 62]



In [67]:
y2 = x8.reshape(2,4)

print(y2, end='\n\n')


[[18 34 77 97]
 [89 58 20 62]]



In [68]:
z2 = x8.reshape(2,2,2)

print(z2, '\n\n')

[[[18 34]
  [77 97]]

 [[89 58]
  [20 62]]] 




In [69]:
x9= np.array([[-1, 1], [-3, 3]])
y3 = np.array([[-2, 2], [-4, 4]])

In [70]:
np.vstack((x9,y3))

array([[-1,  1],
       [-3,  3],
       [-2,  2],
       [-4,  4]])

In [71]:
x10 = np.array([[-1, 1], [-3, 3]])

y4 = np.array([[-2, 2], [-4, 4]])

z3 = np.array([[-5, 5], [-6, 6]])

In [72]:
np.hstack((x10,y4,z3))

array([[-1,  1, -2,  2, -5,  5],
       [-3,  3, -4,  4, -6,  6]])

In [73]:
x = np.arange(30).reshape(6, 5)
print(x,end='\n\n')


res = np.vsplit(x, 2)

print(res[0], end='\n\n')

print(res[1])


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [74]:
x = np.arange(30).reshape(6, 5)

print(x,end='\n\n')

res = np.vsplit(x, (2, 5))

print(res[0], end='\n\n')

print(res[1], end='\n\n')

print(res[2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[25 26 27 28 29]]


In [75]:
x = np.arange(10).reshape(2, 5)
print(x,end='\n\n')


res = np.hsplit(x, (2,4))

print(res[0], end='\n\n')

print(res[1], end='\n\n')

print(res[2])


[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 1]
 [5 6]]

[[2 3]
 [7 8]]

[[4]
 [9]]


In [76]:
x = np.arange(6).reshape(2,3)
print(x)
y = np.hsplit(x,(2,))
print(y[0])

[[0 1 2]
 [3 4 5]]
[[0 1]
 [3 4]]


In [77]:
x=np.arange(20)
print(x.shape)

(20,)


In [78]:
y=x.reshape((2, 10))
print(x,end='\n\n')
print(y,end='\n\n')
np.hsplit(y,2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]



[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]]), array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]])]

In [79]:
z=x.reshape((4, 5))
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [80]:
np.vsplit(z,2)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [81]:
x=np.arange(3,15,3)
print(x)

[ 3  6  9 12]


In [82]:
p=x.reshape(2,2)
print(p)

[[ 3  6]
 [ 9 12]]


In [83]:
x=np.arange(15,33,3)
print(x)

[15 18 21 24 27 30]


In [84]:
q=x.reshape(2,3)
print(q)

[[15 18 21]
 [24 27 30]]


In [85]:
np.hstack((p,q))

array([[ 3,  6, 15, 18, 21],
       [ 9, 12, 24, 27, 30]])

In [86]:
x = np.arange(6).reshape(2,3)
print(x, end='\n\n')


print(x + 10, end='\n\n')

print(x * 3, end='\n\n')

print(x % 2)

[[0 1 2]
 [3 4 5]]

[[10 11 12]
 [13 14 15]]

[[ 0  3  6]
 [ 9 12 15]]

[[0 1 0]
 [1 0 1]]


In [87]:
x = np.array([[-1, 1], [-2, 2]])

y = np.array([[4, -4], [5, -5]])



print(x + y, end='\n\n')

print(x * y)


[[ 3 -3]
 [ 3 -3]]

[[ -4  -4]
 [-10 -10]]


In [88]:
x = np.array([[-1, 1], [-2, 2]])

y = np.array([-10, 10])
print(x * y)

[[10 10]
 [20 20]]


In [89]:
x = np.array([[0,1], [2,3]])



print(np.square(x), end='\n\n')

print(np.sin(x))

[[0 1]
 [4 9]]

[[0.         0.84147098]
 [0.90929743 0.14112001]]


In [90]:
x = np.array([[0,1], [2, 3]])



print(x.sum(), end='\n\n')

print(x.sum(axis=0), end='\n\n')

print(x.sum(axis=1))


6

[2 4]

[1 5]


In [91]:
x = np.arange(4)
y = np.arange(4)

print(x == y)

[ True  True  True  True]


In [92]:
print(np.repeat(3, 4))

[3 3 3 3]


In [93]:
x = np.array([[-2], 
              [2]])
y = np.array([[-3, 3]])
print(x.dot(y))

[[ 6 -6]
 [-6  6]]


In [94]:
x = np.arange(30).reshape(5,6)
print(x.argmax(axis=1))

[5 5 5 5 5]


In [95]:
x = np.arange(4).reshape(2,2)
print(np.isfinite(x))

[[ True  True]
 [ True  True]]


In [96]:
y=np.arange(6).reshape((2, 3))
print(y)

[[0 1 2]
 [3 4 5]]


In [97]:
np.square(y)+5

array([[ 5,  6,  9],
       [14, 21, 30]], dtype=int32)

In [98]:
x=np.random.randint(-30,30,size=(5, 6))
print(x)

[[  4  23 -28   4 -16   4]
 [ 19  18  -6 -15   6  13]
 [ 28 -14  29 -21  -1  -8]
 [-28  -3  14 -26   1 -29]
 [-17  23 -11   6 -26  -3]]


In [99]:
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

[  6  47  -2 -52 -36 -23]
[ -9  35  13 -71 -28]


In [100]:
x=10+2*np.random.randn(50)
print(x)

[11.96113829 12.75399262  9.53942983 10.96184823  7.46617884 10.54201018
 14.28152645 10.95073808 10.49304978  7.83165209  5.23683481  9.12730241
  5.85517628  7.40912032  9.07195283  9.88594673 10.55185947 12.98903044
 11.13364127  5.39325148 12.75400144  7.62522636 10.15878611 10.21593725
 11.01390221 12.25117872  7.98389503 10.70965845  8.59466363 10.22690226
  7.91773259  8.6268013   4.88110483 11.8926211  11.58134331 11.36000379
 11.43321164 10.95540969  8.66752014 10.16896016  9.32247901 11.41184236
  6.79647719 10.78649614  8.79668464 13.67595503  9.96011525 10.8424968
  9.60938118  9.56745523]


In [101]:
print(np.mean(x),np.std(x),np.var(x))

9.864478465776381 2.1117061994062296 4.4593030726107035


In [102]:
x = np.array([5, 10, 15, 20, 25, 30, 35])

print(x[1])  # Indexing

print(x[1:6]) # Slicing

print(x[1:6:3]) # Slicing


10
[10 15 20 25 30]
[10 25]


In [103]:
y = np.array([[0, 1, 2],

              [3, 4, 5]])

print(y[1:2, 1:3]) 

print(y[1])   

print(y[:, 1]) 

[[4 5]]
[3 4 5]
[1 4]


In [104]:
z = np.array([[[-1, 1], [-2, 2]],

              [[-4, 4], [-5, 5]],

              [[-7, 7], [-9, 9]]])

print(z[1,:,1])

print(z[1:,1,:])

print(z[2])


[4 5]
[[-5  5]
 [-9  9]]
[[-7  7]
 [-9  9]]


In [105]:
x = np.array([[-1, 1], [-2, 2]])



for row in x:

    print('Row :',row)

Row : [-1  1]
Row : [-2  2]


In [106]:
x = np.array([[0,1], [2, 3]])



for a in np.nditer(x):

    print(a)


0
1
2
3


In [107]:
x = np.arange(10).reshape(2,5)



condition = x % 2 == 0

print(condition)



print(x[condition])

[[ True False  True False  True]
 [False  True False  True False]]
[0 2 4 6 8]


In [108]:
x = np.arange(12).reshape(3,4)
print(x[-1:,].shape)

(1, 4)


In [109]:
print(x[-2])

[4 5 6 7]


In [110]:
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x[[0, 1, 2], [0, 1, 1]])

[1 4 6]


In [111]:
x = np.arange(30).reshape(3,5,2)
print(x)
print(x[1,::2,1])

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]
[11 15 19]


In [112]:
x = np.array([[0, 1], [1, 1], [2, 2]])
y = x.sum(-1)
print(x[y < 2, :])

[[0 1]]


In [113]:
x = np.arange(30).reshape(6, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [114]:
print(x[-1])

[25 26 27 28 29]


In [115]:
x=np.arange(30).reshape(2, 3, 5)
print(x)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [116]:
b=np.array([True,False])
b.shape

(2,)

In [117]:
x[b]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [118]:
x[b,:,1:3]

array([[[ 1,  2],
        [ 6,  7],
        [11, 12]]])

In [119]:
x[b,2,1:3]

array([[11, 12]])

In [120]:
x = np.array([[-1,0,1], [-2, 0, 2]])

y = np.zeros_like(x)
print(y)

[[0 0 0]
 [0 0 0]]


In [121]:
x = np.arange(30).reshape(3,5,2)
print(x[1,::2,1])

[11 15 19]


In [122]:
x = np.arange(4)
print(x.flatten())

[0 1 2 3]


In [123]:
x = np.arange(6).reshape(2,3)

y = np.hsplit(x,(2,))
print(y[0])

[[0 1]
 [3 4]]


In [124]:
x = np.arange(12).reshape(3,4)
print(x[:,1])

[1 5 9]


In [125]:

x = np.array([[-2], 
              [2]])
y = np.array([[-3, 3]])
print(x + y)

[[-5  1]
 [-1  5]]


In [126]:
x = np.array([[3.2, 7.8, 9.2],
             [4.5, 9.1, 1.2]], dtype='int64')
print(x.itemsize)

8


In [127]:
x = np.arange(30).reshape(3,5,2)
print(x[-1, 2:-1, -1])

[25 27]
