# Constants and Sessions

In [0]:
import tensorflow as tf

In [0]:
a1 = tf.constant([4,3,2,1])
a2 = tf.constant([1,3,4,7])

In [0]:
res = tf.multiply(a1, a2)

In [0]:
sess = tf.Session()

In [6]:
print(sess.run(res))

[4 9 8 7]


In [0]:
sess.close()

# Handling Session Efficiently

In [8]:
with tf.Session() as sess:
  finalOutput = sess.run(res)
  print(finalOutput)


[4 9 8 7]


# Constants Structure

Constants are created using the **constant()** function.

constant(**value**, ***dtype***=None, ***shape***=None, ***name***='Const', ***verify_shape***=False)


1.   value - Can take any assigned value
2.   dtype - Data Type (float / integer)
3.   shape - this is optional , it takes the dimensions
4.   name - can assign any name to the constant
5.   verify_shape - another optional parameter that verifies the dimension of the constant.


In [0]:
x = tf.constant(42, name="a", dtype=tf.float32)

# Variables

In TensorFlow all the variables are in-memory buffers that have tensors. These tensors require initialization to be consumed in the data flow graph.


1.   Variables become a part of the graph by calling the **variable()** construct.
2.   They are used to keep and update the parameters used in the models.


In [0]:
a = tf.Variable(tf.zeros([5]), name="a")
z = tf.Variable(tf.add(x,a), trainable=False)

# Placeholders

Placeholders are values that are initially unassigned but get initialized when the session is invoked.


*   The main use of placeholders is they allow the creation of operations and the computational graph sans needing to provide the data before that.
*   The required data can be added during the actual runtime from any external sources.

placeholder(**dtype**, ***shape***=None, ***name***=None)



# HandOn for Tensor matrix operation

Using numpy initialize two matrix with values **[1,3,4],[3,5,3],[4,5,3]** and **[2,5,7],[3,6,8],[2,6,9]** as **matrix1** and **matrix2** respectively

In [0]:
import numpy as np

matrix1 = np.array([[1,3,4],[3,5,3],[4,5,3]])
matrix2 = np.array([[2,5,7],[3,6,8],[2,6,9]])

covert **matrix1** and **matrix2** to tensorflow object and call them as **tf_mat1** and **tf_mat2**, make sure to specify datatype as "**float64**"

In [0]:
tf_mat1 = tf.constant(matrix1,dtype=tf.float64)
tf_mat2 = tf.constant(matrix2,dtype=tf.float64)

initilise tensorflow variables **a** and **b** with matrix **tf_mat1** and **tf_mat2** respectively. Also **initialize all the variables** before performing the operation.(using** initialize_all_variables()**)

In [0]:
a = tf.Variable(tf_mat1)
b = tf.Variable(tf_mat2)
init = tf.global_variables_initializer() # warning comes when using initialize_all_variables

Perform elementwise **matrix multiplication** on **a**, b **bold text** and assign it to **final_mat1** variable

In [0]:
final_mat1 = tf.multiply(a,b)
determinant1 = tf.matrix_determinant(final_mat1)


Perform **dot product** on matrix** a**, and transpose of** b **

In [0]:
b_inv = tf.transpose(b)
final_mat2 = tf.matmul(a,b_inv)
determinant2 = tf.matrix_determinant(final_mat2)

Final Exceution tensorflow using session

In [22]:
with tf.Session() as sess:
    sess.run(init)
    print("elementwise matrix multiplication ", sess.run(final_mat1))
    print("dot product ", sess.run(final_mat2))
    print("determinant1 %f\n" % sess.run(determinant1))
    print("determinant2 %f" % sess.run(determinant2))    

elementwise matrix multiplication  [[ 2. 15. 28.]
 [ 9. 30. 24.]
 [ 8. 30. 27.]]
dot product  [[45. 53. 56.]
 [52. 63. 63.]
 [54. 66. 65.]]
determinant1 255.000000

determinant2 11.000000


# Tensor Parameters
Any tensor can be identified with the help of the following three parameters:


*   **Rank**: This specifies the number of dimensions of the tensor.
*   **Shape**: The number of rows and columns in a tensor.
*   **Type**: The datatype that is carried by the tensor.

Tensors can be built using NumPy arrays and can be converted into a tensor object.

# Tensors convertion from NumPy arrays

### 1D tensors can be built in the following manner:

In [25]:
tensor_1d = np.array([1,2,3,4,5])

print (tensor_1d)


[1 2 3 4 5]


### Getting the Dimensions:

In [26]:
print (tensor_1d.ndim)

1


### Getting the Shape:

In [27]:
print (tensor_1d.shape)

(5,)


### Getting the Data Type

In [28]:
print (tensor_1d.dtype)

int64


### Convert to Tensors 1D

Any NumPy array can be converted to a tensor in the following way.

In [30]:
tensor1d = tf.convert_to_tensor(tensor_1d, dtype=tf.int64)

with tf.Session() as session:
    print(session.run(tensor1d))
    print(session.run(tensor1d[0]))
    print(session.run(tensor1d[1]))

[1 2 3 4 5]
1
2


### 2D Tensors

Creating a 2d array

In [31]:
array_2d_1 = np.array(np.arange(16).reshape(4,4), dtype='int32')
print(array_2d_1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### Attributes of Array

The array has two dimensions.

In [32]:
print("dimensions, rows and columns,The datatype",array_2d_1.ndim,array_2d_1.shape,array_2d_1.dtype)

dimensions, rows and columns,The datatype 2 (4, 4) int32


### Converting to Tensors 2D

Converting the 2d array to rank 2 tensor

In [33]:
tensor_2d_1 = tf.convert_to_tensor(array_2d_1)


with tf.Session() as session:
    print (session.run(tensor_2d_1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


# Matrix Operations with Tensors

## Matrix Addition

### Initializing the Array

In [38]:
array_2d_1 = np.array(np.arange(16).reshape(4,4), dtype='int32')
array_2d_2 = np.array(np.arange(16,32).reshape(4,4), dtype='int32')
print(array_2d_1)
print(array_2d_2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


### Converting to Tensors

In [0]:
tensor_2d_1 = tf.convert_to_tensor(array_2d_1)
tensor_2d_2 = tf.convert_to_tensor(array_2d_2)

### Matrix Operation

In [0]:
mat_add = tf.add(tensor_2d_1, tensor_2d_2)

### Executing the Session

In [37]:
with tf.Session() as session:
    print (session.run(mat_add))

[[16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]


## Matrix Multiplication

### Initializing the Array

In [0]:
array_2d_1 = np.array(np.arange(16).reshape(4,4), dtype='int32')
array_2d_2 = np.array(np.arange(16,32).reshape(4,4), dtype='int32')

### Converting to Tensors

In [0]:
tensor_2d_1 = tf.convert_to_tensor(array_2d_1)
tensor_2d_2 = tf.convert_to_tensor(array_2d_2)

### Matrix Operation

In [0]:
mat_mul = tf.matmul(tensor_2d_1, tensor_2d_2)

### Executing the Session

In [42]:
with tf.Session() as session:
    print (session.run(mat_mul))

[[ 152  158  164  170]
 [ 504  526  548  570]
 [ 856  894  932  970]
 [1208 1262 1316 1370]]


## Determinant of a Matrix

### Initializing the Array

In [0]:
array_2d_1 = np.array(np.arange(16).reshape(4,4), dtype='float64')

### Converting to Tensors

In [0]:
tensor_2d_1 = tf.convert_to_tensor(array_2d_1)

### Matrix Operation

In [0]:
mat_det = tf.matrix_determinant(tensor_2d_1)

### Executing the Session

In [53]:
with tf.Session() as session:
    print (session.run(mat_det))

-2.9582283945787796e-30


# Linear Regression Model

## Model Building Steps


*   Define the relationship between **x** and **y** .
*   Generate random data points points.
*   Define a cost function that calculates the error between the actual and predicted values
*   Optimize the cost function using gradient descent algorithm.
*   Iterate this optimization process till the values converge.

## Data Creation

### Initializing the number of points and the dependent and independent variables.

In [0]:
numPts = 100
x = []
y = []

### Assigning the values for a and b .

In [0]:
a = 0.45
b = 0.60

**y=0.45∗x+0.60**

Finally, after gradient descent, the model should also converge to the above values of **a **and **b**.

## Generating Values
The below code is used to generate random points for xx and yy



In [0]:
for i in range(numPts):
    xtemp = np.random.normal(0.0,0.5)
    ytemp = a*xtemp + b +np.random.normal(0.0,0.1)
    x.append([xtemp])
    y.append([ytemp])

## Initializing the Variables

*   The objective here is to implement a Machine Learning algorithm to predict using TensorFlow which must predict **y** given **x**.
*   The linear regression model should converge to an optimal aa and bb that minimizes the cost function.

### Initializing arbitrary values for A and setting b to zero.

In [0]:
A = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.zeros([1]))

### Creating a relationship between xx and yy

In [0]:
yPred = tf.add(tf.multiply(A, x), b)

### Cost Func and Grad Desc

The below code is used to set the learning rate. It can be set to any number between 0 and 1.

In [0]:
learningRate = 0.25

Below the cost function is defined. The optimization is done using gradient descent. Finally, the model is trained to minimize the cost function.

In [0]:
cost_function = tf.reduce_mean(tf.square(yPred - y))
optimizer = tf.train.GradientDescentOptimizer(learningRate)
train = optimizer.minimize(cost_function)

### Testing the Model

In [0]:
NumIter = 50
model = tf.initialize_all_variables()

with tf.Session() as session:
        session.run(model)

        for step in range(0,NumIter):
            session.run(train)
        ModelA = session.run(A)
        ModelB = session.run(b)

# Hands on Linear regression

Given a vector of input and output data, you need to find the linear relationship between these two data which is in the form
**y=w∗x+b**

Using numpy initialise training input data **trainX** with values **[4.4,7.2,3.712,6.42,4.168,8.79,7.88,7.59,2.167,7.042,10.71,5.33,9.97,5.64,9.27,3.1,3.9]**

**trainY** with values **[2.28644, 3.25412, 2.0486672, 2.984552, 2.2062608, 3.803624 ,3.489128, 3.388904 ,1.5147152, 3.1995152, 4.467176, 2.607848 ,4.211432, 2.714984, 3.969512, 1.83716, 2.11364]**


In [0]:
import numpy.random as rand

trainX = np.array([4.4,7.2,3.712,6.42,4.168,8.79,7.88,7.59,2.167,7.042,10.71,5.33,9.97,5.64,9.27,3.1,3.9])
                         
trainY = np.array([2.28644, 3.25412, 2.0486672, 2.984552, 2.2062608, 3.803624 ,3.489128, 3.388904 ,1.5147152, 3.1995152, 4.467176, 2.607848 ,4.211432, 2.714984, 3.969512, 1.83716, 2.11364])

num_samples = trainX.shape[0]

Define placeholders for input and output data as **X** and **Y** . Let them be of data type **float32**

In [0]:
X = tf.constant(trainX,dtype=tf.float32)
Y = tf.constant(trainY,dtype=tf.float32)

Since this is a linear regression problem the output will be in the form of  **w * trainX + b**

Initialse** w** and **b** with random values using **rand.randn()** function. Make sure you declare them as **tensorflow variables**

In [0]:
w = tf.Variable(np.array(rand.randn(1)))
b =  tf.Variable(np.array(rand.randn(1)))

implement  **X * W + b** using appropriate tensorflow functions to predict the output **Y**.

Train the model using gradient descent to minimize the cost. Initialize the number of iterations and learning rate

**TIP**: start with small learning rate and large iteration.

In [0]:
num_iter = 10000 
learning_rate = 0.01


pred = tf.add(tf.multiply(w,trainX),b)
cost = tf.reduce_mean(tf.square(pred - trainY))

optimizer = tf.train.GradientDescentOptimizer(learning_rate)
train = optimizer.minimize(cost)


Execute the below piece of code.

In [85]:
model = tf.global_variables_initializer()
with tf.Session() as session:
    session.run(model)
    for i in range(num_iter):
        session.run(train, feed_dict={X: trainX , Y: trainY})
    w = session.run(w)
    b = session.run(b)
    print( w)
    print( b)

[0.3456]
[0.7658]


# Logistic Regression

## Steps

*   The weights and bias values are initialized to arbitrary values.
*  Based on the values, the output is calculated. The actual value of the output is compared to the calculated value. The error value is used to adjust the weights and biases.
*  This process is repeated till the values converge and the error is minimized.




